name: Docker Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Docker
        uses: jamescurtin/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.10
          subcommand: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snake_apk
          path: bin/*.apk
          
